name: Evolene CI

on:  
  schedule:
    - cron: "0 0 * * *"
  push:
    paths-ignore:
          - '*.md'
          - '*.png'
  workflow_dispatch:

jobs:

  Evolene:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Evolene CI pipeline steps
        shell: bash
        env:
          BUILD_INFORMATION_OUTPUT_FILE: "/version.conf"  # Create a file with the build information
          SLACK_CHANNELS: "#team-studadm-build"           # List of Slack channels for user information
          PUSH_PUBLIC: True

        run: |
          ${{ secrets.EVOLENE_RUN_COMMAND }}
